### ISSUE TITLE
Compatibility with toc permalinks (section numbers are duplicated)

### ISSUE THREAD

**Issue by spanglerco** [timvink/mkdocs-enumerate-headings-plugin#23]
When using [a toc configuration](https://python-markdown.github.io/extensions/toc/#usage) like this:

```yaml
markdown_extensions:
  - toc:
      permalink: true

plugins:
  - enumerate-headings:
      toc_depth: 4
```

The headings end up with duplicate section numbers in the permalink itself. For example:

```html
<h2 id="table-of-contents"><span class="enumerate-heading-plugin">1.1</span> Table of Contents<a class="headerlink" href="#table-of-contents" title="Permanent link">1.1 ¶</a></h2>
```

I believe this is caused by this function:

https://github.com/timvink/mkdocs-enumerate-headings-plugin/blob/c4951da2fadefac8c7bb716e4ef5d68c11850472/mkdocs_enumerate_headings_plugin/html_page.py#L28

Which iterates every anchor on the page that links to the section instead of only iterating over anchors in the nav bar. I was able to work around this using anchorlinks instead of permalinks plus extra CSS to hide the enumerate-heading-plugin span.
