### ISSUE TITLE
Incorrect reference to CSS class in README.md

### ISSUE THREAD

**Issue by morido** [timvink/mkdocs-enumerate-headings-plugin#24]
[README.md](https://raw.githubusercontent.com/timvink/mkdocs-enumerate-headings-plugin/master/README.md) states:

```css
/* Extra CSS for mkdocs-enumerate-headings-plugin */ 
.enumerate-headings-plugins {
  /* 100% is baseline so 250% is a lot lighter */
  filter: brightness(250%);
}
```

However, as per [heading.py](https://github.com/timvink/mkdocs-enumerate-headings-plugin/blob/master/mkdocs_enumerate_headings_plugin/heading.py) the CSS class is called `enumerate-heading-plugin`, I.e. the code block should be:

```css
/* Extra CSS for mkdocs-enumerate-headings-plugin */ 
.enumerate-heading-plugin {
  /* 100% is baseline so 250% is a lot lighter */
  filter: brightness(250%);
}
```

Also `filter: brightness(250%);` did not cause any noticeable effect using the default settings of the material theme. I opted for `filter: opacity(35%);` instead.
