### ISSUE TITLE
Sub-number pages within sections

### ISSUE THREAD

**Issue by mfoulds** [timvink/mkdocs-enumerate-headings-plugin#34]
Thanks for this great plug-in, and for [mkdocs-print-site-plugin](https://github.com/timvink/mkdocs-print-site-plugin).

Is there a way to give sections a number, and then treat subsidiary pages as sub-pages? For example, if we had this `nav` structure:

```yaml
nav
  - "Section 1":
    - 'Page 1.1': 'section1_page_1.md'
    - 'Page 1.2': 'section1_page_2.md'
  - "Section 2":
    - 'Page 2.1': 'section1_page_1.md'
    - 'Page 2.2': 'section1_page_2.md'
    - "Subsection 2.3":
      - "Page 2.3.1": "subsection_2.3.1_page.md"
 ```

Currently, `Page 1.1` will be numbered as `1`, `Page 2.2` numbered as `4`, etc. "Page 2.3.1" will be numbered as `4.1`.

I couldn't find a way to treat sections as numbers, and the pages as subsections, as per the names shown in the example above. If there's no current option, is it a common enough use case to warrant an enhancement?
